### ISSUE TITLE
Better README/docs

### ISSUE THREAD

**Issue by cyan-ice** [cyan-ice/saturday#1]
The README file is temporary, and probably will be removed soon.
This issue is about a replacement to the legacy README file. Feel free to work on this.

**Comment by cyan-ice** [comment]
The new README might include a quick tutorial, installation & execution, and a link to the wiki.

**Comment by BDadmehr0** [comment]
I want to do it

**Comment by BDadmehr0** [comment]
The pull request has been approved. Is there anything else that needs to be added that you have not closed this issue? @cyan-ice

**Comment by cyan-ice** [comment]
Sorry, I had two very busy school weeks.
@BDadmehr0
