### ISSUE TITLE
Delete executable files

### ISSUE THREAD

**Issue by BDadmehr0** [cyan-ice/saturday#7]
It is reasonable to upload executable files in Releases and only source code in the repo because this will increase the size of the repo.

**Comment by cyan-ice** [comment]
You're right. But we're keeping the executables until I have a script to generate the executable (e.g. using pyinstaller), because I want people to be able to access the executable by cloning our repo or downloading from the releases.

**Comment by BDadmehr0** [comment]
> You're right. But we're keeping the executables until I have a script to generate the executable (e.g. using pyinstaller), because I want people to be able to access the executable by cloning our repo or downloading from the releases.

Do you want me to write a script that creates an executable file for the desired operating system?

**Comment by cyan-ice** [comment]
Sure.
@BDadmehr0

**Comment by BDadmehr0** [comment]
https://github.com/cyan-ice/saturday/pull/9
